import Auth0 from 'auth0-js'
import { AUTH_CONFIG } from './credentials'

export default class UserService {
  auth0Manage = new Auth0.Management({
    domain: AUTH_CONFIG.domain,
    token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik5rSTRSVVpHUVRjeE16RTRNRUZHTkVJeFFUQXlNVEpEUTBaQk0wRTRRVEkyUWpFNVEwTXdSUSJ9.eyJpc3MiOiJodHRwczovL2NoZW1heGEuZXUuYXV0aDAuY29tLyIsInN1YiI6InhBQ0FFOHZIYU93MzhlYzIxMnlOeDlaa0F2M2ZndDVuQGNsaWVudHMiLCJhdWQiOiJodHRwczovL2NoZW1heGEuZXUuYXV0aDAuY29tL2FwaS92Mi8iLCJleHAiOjE0OTc1MzI2NjIsImlhdCI6MTQ5NzQ0NjI2Miwic2NvcGUiOiJyZWFkOmNsaWVudF9ncmFudHMgY3JlYXRlOmNsaWVudF9ncmFudHMgZGVsZXRlOmNsaWVudF9ncmFudHMgdXBkYXRlOmNsaWVudF9ncmFudHMgcmVhZDp1c2VycyB1cGRhdGU6dXNlcnMgZGVsZXRlOnVzZXJzIGNyZWF0ZTp1c2VycyByZWFkOnVzZXJzX2FwcF9tZXRhZGF0YSB1cGRhdGU6dXNlcnNfYXBwX21ldGFkYXRhIGRlbGV0ZTp1c2Vyc19hcHBfbWV0YWRhdGEgY3JlYXRlOnVzZXJzX2FwcF9tZXRhZGF0YSBjcmVhdGU6dXNlcl90aWNrZXRzIHJlYWQ6Y2xpZW50cyB1cGRhdGU6Y2xpZW50cyBkZWxldGU6Y2xpZW50cyBjcmVhdGU6Y2xpZW50cyByZWFkOmNsaWVudF9rZXlzIHVwZGF0ZTpjbGllbnRfa2V5cyBkZWxldGU6Y2xpZW50X2tleXMgY3JlYXRlOmNsaWVudF9rZXlzIHJlYWQ6Y29ubmVjdGlvbnMgdXBkYXRlOmNvbm5lY3Rpb25zIGRlbGV0ZTpjb25uZWN0aW9ucyBjcmVhdGU6Y29ubmVjdGlvbnMgcmVhZDpyZXNvdXJjZV9zZXJ2ZXJzIHVwZGF0ZTpyZXNvdXJjZV9zZXJ2ZXJzIGRlbGV0ZTpyZXNvdXJjZV9zZXJ2ZXJzIGNyZWF0ZTpyZXNvdXJjZV9zZXJ2ZXJzIHJlYWQ6ZGV2aWNlX2NyZWRlbnRpYWxzIHVwZGF0ZTpkZXZpY2VfY3JlZGVudGlhbHMgZGVsZXRlOmRldmljZV9jcmVkZW50aWFscyBjcmVhdGU6ZGV2aWNlX2NyZWRlbnRpYWxzIHJlYWQ6cnVsZXMgdXBkYXRlOnJ1bGVzIGRlbGV0ZTpydWxlcyBjcmVhdGU6cnVsZXMgcmVhZDplbWFpbF9wcm92aWRlciB1cGRhdGU6ZW1haWxfcHJvdmlkZXIgZGVsZXRlOmVtYWlsX3Byb3ZpZGVyIGNyZWF0ZTplbWFpbF9wcm92aWRlciBibGFja2xpc3Q6dG9rZW5zIHJlYWQ6c3RhdHMgcmVhZDp0ZW5hbnRfc2V0dGluZ3MgdXBkYXRlOnRlbmFudF9zZXR0aW5ncyByZWFkOmxvZ3MgcmVhZDpzaGllbGRzIGNyZWF0ZTpzaGllbGRzIGRlbGV0ZTpzaGllbGRzIHVwZGF0ZTp0cmlnZ2VycyByZWFkOnRyaWdnZXJzIHJlYWQ6Z3JhbnRzIGRlbGV0ZTpncmFudHMgcmVhZDpndWFyZGlhbl9mYWN0b3JzIHVwZGF0ZTpndWFyZGlhbl9mYWN0b3JzIHJlYWQ6Z3VhcmRpYW5fZW5yb2xsbWVudHMgZGVsZXRlOmd1YXJkaWFuX2Vucm9sbG1lbnRzIGNyZWF0ZTpndWFyZGlhbl9lbnJvbGxtZW50X3RpY2tldHMgcmVhZDp1c2VyX2lkcF90b2tlbnMifQ.Yc7WfwTWpofu_3AoiMPWmmyVZ-POONu_d9ZcQ5HSHJjACgufB9tHQHFALucFv0cCuad9YCG4di12YYGAgKNSMwoSmNvgFYQwFmUh7gHYqNMOOcEoqVxd9ECU8MB4USUGKKEcHhzYOWTdvRYBKXghnlJZZ4uyydptjqon2u-6Zrfz1tLvw5bmLwl9eSHzXzmquJmiUCnaSKvZuuUj2cw5wxDTAQecmE78JllBZOdcg8AStSZe9AQiUu7kzxLRbVhu07uk5GN4kY9cQDaRVOu_d5XGECUuAB5z3dWadX829l9CABySKv_MaIDuRAffFg8W6f7NsNsM6moJCAq51TZdgQ'
  })
  userData

  constructor () {
    this.getUserData = this.getUserData.bind(this)
  }

  getUserData (cb) {
    const userId = localStorage.getItem('sub')
    let self = this
    this.auth0Manage.getUser(userId, (err, data) => {
      if (data) {
        self.userData = data
      }
      cb(err, data)
    })
  }
}
